Genera la clave privada

openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048

Extrae la clave pública

openssl rsa -pubout -in private_key.pem -out public_key.pem



##### push no encuentra trjeta

POST http://localhost:9095/encrypt
Content-Type: application/json

{
    "id":11,
    "name":"info encryptda"
}



####

POST http://localhost:9095/decrypt
Content-Type: application/json

{
    "token":"eyJ0eXAiOiJKT1NFIiwiZW5jIjoiQTI1NkdDTSIsImlhdCI6IjE2MjUwNTc4OTYiLCJhbGciOiJSU0EtT0FFUC0yNTYiLCJraWQiOiJ0a24uaXMuandlLjEifQ.F3zVPx2zoe1OnP1furKuU9v3O5Q4iN2rYB-rZjyoc3poylnMBc7Bn_yBxO7YB6PBqKh4Li2gyrKHCne26tTNT8YFLQB9r5JfiCe0sF_1qFV3xq4g5MufeRamfjwWsVcQHu3YBivc5Qlnv0rhT3BuUfrQe_svBvCHRDeJXPTKlqYSxpf4yLNMY5xNxd_ld66i0lBbsIu2KrkuYSRpI4wqDr1RW2Z3r3UHmlA-TZNziFwcDitVgubH8bLjOvbk9G2QaoG5LJjiNlQ0HVPj_kXjK80wRXN7wahd-doMK3SKTjKvDnkWsWrEScMyvY5swKyYICnYlS6idNT-3dcpQDQlIQ.XVVUCuJkdmKUbjFi.FdyQmA1O5Yze2Outu5zOWhuOXcLRLUNs8PhNbhZhgGDp.shOAEzwB2nt9A8Ojb5lo4w"
}
